services:
- type: web
  name: ttravel-hospitality
  env: node
  plan: starter
  buildCommand: npm run build
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    fromService: web